#!/bin/bash

set -e

# -- global vars
TARGET=${1:-~/coffee-accounting}
RED=$(tput setaf 1)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
SGR0=$(tput sgr0)
SUDO=$(command -v sudo)

# -- helper functions
trace() { # message ... 
	printf "%s * %s%s\n" "$BLUE" "$*" "$SGR0"
	}
fatal() { # exit-message ...
	printf "\n%s: %s%s\n" "$RED${0##*/}" "$BOLD$*" "$SGR0" >&2
	exit 4 
	}
edit() { # prompt default-value ...
        local PS="${1:-}"
        shift
        local VAL="${1:-}"
        while [ $# -gt 0 ]; do history -s -- "$1"; shift; done
        #printf "Press up arrow to edit current value: %s\n" "$string"
        read -ep "$PS: " -i "$VAL"
        }
root_do() { # prompt command args...
	msg=$1 ; shift
	if [ -n "$SUDO" ] ; then
		sudo -p "$msg, please enter your password: " $*
	else
		if [ "`id -u`" != 0 ] ; then
			echo "$msg, please enter root password..."
		fi
		su -c "$*"
	fi
	}

#TMP="$(mktemp "${0##*/}.XXXXXXXXXX")"
#cleanup() { [ -e "$TMP" ] && fatal "unexpected end of script, plz rm $TMP"; }
#trap 'cleanup' EXIT
#trace "using temporary file $TMP"

# trace "here we are..."
trap 'fatal "*** script aborted ***"' INT
cat <<INFO
This will install coffee-accounting and all requirements
inside a python virtual environment. To cancel press ^C.
INFO

trace "Checking required system dependencies..."
MISSING=()
[ -x "$(command -v python2.7)" ] || MISSING+=('python2.7')
[ -x "$(command -v pdflatex)" ] || MISSING+=('texlive')
[ -x "$(command -v pip)" ] || MISSING+=('python-pip')
[ -x "$(command -v virtualenv)" ] || MISSING+=('virtualenv')
[ "$MISSING" ] && echo "Missing packages are: ${MISSING[@]}"

trace "Reading installation directory"
edit "Installation Directory" "$TARGET" "$(pwd)"
TARGET=$REPLY
[ -e "$TARGET" ] && fatal "$TARGET exists, aborting installation"

trace "Creating install dir: $TARGET"
mkdir -p "$TARGET" 
[ -e "$TARGET" ] || fatal "could not create install dir $TARGET"

if [ "$MISSING" ]; then
	trace "Found missing packages: $MISSING"
	root_do "Installing dependencies" apt install ${MISSING[@]}
fi

trace "Setting up virtual environment..."
python2.7 -m virtualenv "$TARGET/venv"

trace "Activating virtual environment..."
source "$TARGET/venv/bin/activate"

trace "Installing python requirements..."
pip install -r requirements.txt 

trace "Installing sources..."
cp -r python/ "$TARGET"
cp coffee "$TARGET"

trace "Installation complete!"
cat <<USAGE
call: $TARGET/coffee  to launch the application
or creat symlink, eg.: ln -s "$TARGET/coffee" ~/bin/coffee
USAGE

